//! make バックエンド。
//!
//! ninja 以外の生成器がこの層の上に載ることを、実際に載せて確かめるための
//! ものである（[ADR-0018](../../../docs/adr/0018-backend-layer.md)）。
//! 既に make を持つ環境、make しか無い環境で使える。
//!
//! make には ninja に無い制約がある。ターゲットと前提条件の位置に置ける文字が
//! 限られ、空白を含むパスは表現できない。書けないものを書いて黙って別のものを
//! ビルドするより、そのパスを名指して断る。

use crate::action::{breaks_the_line, cannot_spell, ActionKind};
use crate::backend::{Backend, BuildGraph, Step};
use crate::exec::{drive, Failure};
use dowel_support::log_debug;
use std::path::{Path, PathBuf};

pub struct Make;

pub const FILE: &str = "Makefile";

/// make の規則の中で意味を持ってしまう文字。
///
/// 空白は前提条件の区切り、`:` は規則の区切り、`#` は註釈、`$` は変数、
/// `%` はパターン規則、`;` はレシピの開始、`=` は変数代入。エスケープで
/// 逃げられるものもあるが、組み合わせると make の実装ごとに挙動が違う。
const FORBIDDEN: &[char] = &[':', '#', '$', '%', ';', '=', '\\', '*', '?', '[', ']'];

impl Backend for Make {
    fn name(&self) -> &'static str {
        "make"
    }

    fn available(&self, probe: &mut crate::probe::Prober) -> bool {
        probe.responds_to_version("make")
    }

    fn emit(&self, g: &BuildGraph) -> Result<Vec<PathBuf>, Failure> {
        let text = generate(g)?;
        let path = g.build_dir.join(FILE);
        std::fs::create_dir_all(&g.build_dir).and_then(|_| std::fs::write(&path, text)).map_err(
            |e| Failure::of("writing the makefile", path.display().to_string(), e.to_string()),
        )?;
        log_debug!("wrote {}", path.display());
        Ok(vec![path])
    }

    fn run(&self, g: &BuildGraph, jobs: Option<usize>) -> Result<(), Failure> {
        let file = self.emit(g)?.remove(0);
        let mut args = vec!["-f".to_string(), file.display().to_string()];
        if let Some(j) = jobs {
            args.push("-j".into());
            args.push(j.to_string());
        }
        drive("make", &args, &g.build_dir)
    }
}

pub fn generate(g: &BuildGraph) -> Result<String, Failure> {
    let mut out = String::new();
    out.push_str("# Generated by dowel. Do not edit by hand.\n");
    // 既定の暗黙規則と組み込み変数を切る。`.c` から `.o` を作る make 自身の
    // 規則が残っていると、こちらの規則が無い出力を make が勝手に作りにいく。
    out.push_str("MAKEFLAGS += --no-builtin-rules --no-builtin-variables\n");
    out.push_str(".SUFFIXES:\n");
    out.push_str(".DEFAULT_GOAL := all\n");
    out.push_str(".PHONY: all\n\n");

    let defaults = paths(&g.default_outputs)?;
    out.push_str(&format!("all: {}\n\n", defaults.join(" ")));

    for step in &g.steps {
        out.push_str(&rule(g, step)?);
    }

    // depfile は make 自身の形式なので、そのまま読ませる。まだ無い回（初回）は
    // 黙って進む必要があるため `-include` を使う。
    let depfiles: Vec<String> = g
        .steps
        .iter()
        .filter_map(|s| s.depfile.as_ref())
        .map(|p| p.display().to_string())
        .collect();
    if !depfiles.is_empty() {
        let checked = paths(&depfiles.iter().map(PathBuf::from).collect::<Vec<_>>())?;
        for d in checked {
            out.push_str(&format!("-include {d}\n"));
        }
    }
    Ok(out)
}

fn rule(g: &BuildGraph, step: &Step) -> Result<String, Failure> {
    // 1つの規則に複数の出力を書く移植性のある方法が無い。今の計画段は
    // 出力を1つしか作らないため、増えたときに黙って壊れるより先に断る。
    if step.outputs.len() != 1 {
        return Err(Failure::of(
            "generating the makefile",
            step.command_line(),
            format!(
                "the make backend needs exactly one output per step, but `{}` has {}. \
                 `--backend=ninja` has no such limit",
                step.description,
                step.outputs.len()
            ),
        ));
    }
    // レシピは1行である。行を終わらせる文字が命令に在ると、続きは make に
    // とって別の行になり、`missing separator` で止まる——生成した Makefile の
    // 行番号を指す言葉であり、マニフェストのどこが原因かは読み取れない
    // （[ADR-0058](../../../../docs/adr/0058-a-command-a-backend-cannot-spell.md)）。
    // 説明もレシピの1行に入る（`@printf \'%s\\n\' \'<説明>\'`）。命令だけを
    // 見ると、説明を通って同じ `missing separator` が戻る。
    let line = step.command_line();
    for text in [&line, &step.description] {
        let Some(c) = breaks_the_line(text) else { continue };
        return Err(Failure::of(
            "generating the makefile",
            line.clone(),
            cannot_spell("make", "a recipe", c, &step.description),
        ));
    }
    let target = path(&step.outputs[0])?;

    // 前提条件は入力と、依存ステップの出力。依存の出力は入力に現れるのが
    // 普通だが、現れないもの（誰の入力にもならない派生など）を落とさない。
    let mut prereqs = step.inputs.clone();
    for d in &step.deps {
        if let Some(dep) = g.steps.get(*d) {
            prereqs.extend(dep.outputs.iter().cloned());
        }
    }
    prereqs.sort();
    prereqs.dedup();

    let mut out = format!("{target}: {}\n", paths(&prereqs)?.join(" "));
    out.push_str(&format!("\t@printf '%s\\n' {}\n", recipe(&shell_quote(&step.description))));
    if let Some(parent) = step.outputs[0].parent() {
        out.push_str(&format!(
            "\t@mkdir -p {}\n",
            recipe(&shell_quote(&parent.display().to_string()))
        ));
    }
    // 書庫は追記されるため、作り直す前に消す。ninja の `ar` 規則と同じ。
    if step.kind == ActionKind::Archive {
        out.push_str(&format!(
            "\t@rm -f {}\n",
            recipe(&shell_quote(&step.outputs[0].display().to_string()))
        ));
    }
    out.push_str(&format!("\t@{}\n\n", recipe(&step.command_line())));
    Ok(out)
}

/// レシピ行での make エスケープ。`$` だけが make に食われる。
fn recipe(s: &str) -> String {
    s.replace('$', "$$")
}

fn shell_quote(s: &str) -> String {
    crate::action::shell_quote(s)
}

fn paths(ps: &[PathBuf]) -> Result<Vec<String>, Failure> {
    ps.iter().map(|p| path(p)).collect()
}

/// ターゲット・前提条件の位置に書けるパスか。書けなければ、その文字を名指す。
fn path(p: &Path) -> Result<String, Failure> {
    let s = p.display().to_string();
    let bad = s.chars().find(|c| c.is_whitespace() || FORBIDDEN.contains(c));
    match bad {
        None => Ok(s),
        Some(c) => {
            let shown = if c.is_whitespace() { "whitespace".to_string() } else { format!("`{c}`") };
            Err(Failure::of(
                "generating the makefile",
                s.clone(),
                format!(
                    "make cannot name a path containing {shown}: {s}. \
                     `--backend=ninja` builds this project"
                ),
            ))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::Step;
    use crate::toolstyle::Deps;

    fn step(kind: ActionKind, out: &str, inputs: &[&str]) -> Step {
        Step {
            id: 0,
            kind,
            target: "p:t".into(),
            description: "CC a.o".into(),
            program: "cc".into(),
            arguments: vec!["-c".into(), "a.c".into()],
            inputs: inputs.iter().map(PathBuf::from).collect(),
            outputs: vec![PathBuf::from(out)],
            depfile: None,
            deps: vec![],
            cwd: None,
        }
    }

    fn graph(steps: Vec<Step>) -> BuildGraph {
        BuildGraph {
            build_dir: PathBuf::from("/b"),
            steps,
            artifacts: vec![],
            deps: Deps::Depfile,
            default_outputs: vec![PathBuf::from("/b/app")],
            tool_stamps: vec![],
        }
    }

    #[test]
    fn a_command_with_a_newline_is_refused_before_the_makefile_is_written() {
        // 書いてしまうと、失敗するのは make であり、その言葉は生成した
        // Makefile の行番号を指す（ADR-0058）。
        let mut s = step(ActionKind::Generate, "/b/cfg.h", &[]);
        s.arguments = vec!["-c".into(), "printf 'a\nb'".into()];
        let e = generate(&graph(vec![s])).expect_err("a newline is not spellable");
        let text = format!("{e}");
        assert!(text.contains("newline"), "{text}");
        assert!(text.contains("--backend=direct"), "{text}");
    }

    #[test]
    fn a_description_with_a_newline_is_refused() {
        // 説明は `@printf '%s\n' '<説明>'` に入る。命令だけを見ていると
        // ここを素通りし、レシピが2行に割れる——この変更が防ごうとしている
        // `missing separator` そのものになる。
        let mut st = step(ActionKind::Compile, "/b/a.o", &["/s/a.c"]);
        st.description = "CC a\n.o".into();
        let e = generate(&graph(vec![st])).expect_err("a newline is not spellable");
        assert!(format!("{e}").contains("newline"), "{e}");
    }

    #[test]
    fn a_rule_names_its_output_and_its_inputs() {
        let text =
            generate(&graph(vec![step(ActionKind::Compile, "/b/a.o", &["/s/a.c"])])).unwrap();
        assert!(text.contains("/b/a.o: /s/a.c\n"), "{text}");
        assert!(text.contains("all: /b/app\n"), "{text}");
    }

    #[test]
    fn an_archive_is_removed_before_it_is_rebuilt() {
        let text =
            generate(&graph(vec![step(ActionKind::Archive, "/b/lib.a", &["/b/a.o"])])).unwrap();
        assert!(text.contains("rm -f /b/lib.a"), "{text}");
    }

    #[test]
    fn a_path_make_cannot_name_is_refused_rather_than_written() {
        let e =
            generate(&graph(vec![step(ActionKind::Compile, "/b/my dir/a.o", &[])])).unwrap_err();
        assert!(e.stderr.contains("whitespace"), "{e}");
        assert!(e.stderr.contains("--backend=ninja"), "{e}");
    }

    #[test]
    fn a_dollar_in_a_command_is_not_expanded_by_make() {
        let mut s = step(ActionKind::Link, "/b/app", &[]);
        s.arguments = vec!["-DX=$HOME".into()];
        let text = generate(&graph(vec![s])).unwrap();
        assert!(text.contains("$$HOME"), "{text}");
    }
}
