//! ninja バックエンド。既定。
//!
//! コマンドは規則ではなく辺ごとの変数 `$cmd` に置く。フラグの組み立てを
//! ninja の変数展開に分散させず、1箇所（`Step::command_line`）に閉じるためである。
//! ninja 側の引用規則と自前の引用規則が二重に効く事故を避ける。

use crate::action::ActionKind;
use crate::backend::{Backend, BuildGraph};
use crate::exec::{drive, Failure};
use crate::toolstyle::{Deps, SHOW_INCLUDES_PREFIX};
use dowel_support::log_debug;
use std::path::PathBuf;

pub struct Ninja;

pub const FILE: &str = "build.ninja";

impl Backend for Ninja {
    fn name(&self) -> &'static str {
        "ninja"
    }

    fn available(&self, probe: &mut crate::probe::Prober) -> bool {
        probe.responds_to_version("ninja")
    }

    fn emit(&self, g: &BuildGraph) -> Result<Vec<PathBuf>, Failure> {
        let path = g.build_dir.join(FILE);
        std::fs::create_dir_all(&g.build_dir)
            .and_then(|_| std::fs::write(&path, generate(g)))
            .map_err(|e| {
                Failure::of("writing the ninja file", path.display().to_string(), e.to_string())
            })?;
        log_debug!("wrote {}", path.display());
        Ok(vec![path])
    }

    fn run(&self, g: &BuildGraph, jobs: Option<usize>) -> Result<(), Failure> {
        let file = self.emit(g)?.remove(0);
        let mut args = vec!["-f".to_string(), file.display().to_string()];
        if let Some(j) = jobs {
            args.push("-j".into());
            args.push(j.to_string());
        }
        drive("ninja", &args, &g.build_dir)
    }
}

pub fn generate(g: &BuildGraph) -> String {
    let mut out = String::new();
    out.push_str("# Generated by dowel. Do not edit by hand.\n");
    out.push_str("ninja_required_version = 1.10\n\n");

    out.push_str("rule cc\n");
    out.push_str("  command = $cmd\n");
    out.push_str("  description = $desc\n");
    match g.deps {
        // ヘッダ依存は深さ優先の再走査ではなくコンパイラの出力（depfile）から
        // 取る。
        //
        // `deps = gcc` は使わない。あれは読み取った `.d` を `.ninja_deps` へ
        // 畳んで消すため、依存の記録が ninja の実装詳細の中に閉じる。他の
        // バックエンドも同じ `.d` を読んで最新性を判定するので、記録は
        // バックエンドを跨いでディスク上に残す（issue #41）。
        Deps::Depfile => out.push_str("  depfile = $depfile\n\n"),
        // MSVC はコンパイラに記録を書かせない。`/showIncludes` の出力を
        // 拾うのは**実行する側**であり、ここでは ninja がそれを行う
        // （ADR-0027）。`.d` を跨いで共有する形は、書く者がいないので採れない。
        Deps::ShowIncludes => {
            out.push_str("  deps = msvc\n");
            out.push_str(&format!("  msvc_deps_prefix = {SHOW_INCLUDES_PREFIX}\n\n"));
        }
    }

    out.push_str("rule ar\n");
    out.push_str("  command = rm -f $out && $cmd\n");
    out.push_str("  description = $desc\n\n");

    out.push_str("rule link\n");
    out.push_str("  command = $cmd\n");
    out.push_str("  description = $desc\n\n");

    out.push_str("rule transform\n");
    out.push_str("  command = $cmd\n");
    out.push_str("  description = $desc\n\n");

    out.push_str("rule generate\n");
    out.push_str("  command = $cmd\n");
    out.push_str("  description = $desc\n\n");

    for step in &g.steps {
        let outputs: Vec<String> =
            step.outputs.iter().map(|p| path(&p.display().to_string())).collect();
        let inputs: Vec<String> =
            step.inputs.iter().map(|p| path(&p.display().to_string())).collect();
        out.push_str(&format!(
            "build {}: {} {}\n",
            outputs.join(" "),
            step.kind.name(),
            inputs.join(" ")
        ));
        out.push_str(&format!("  cmd = {}\n", value(&step.command_line())));
        out.push_str(&format!("  desc = {}\n", value(&step.description)));
        if step.kind == ActionKind::Compile && g.deps == Deps::Depfile {
            match &step.depfile {
                Some(d) => {
                    out.push_str(&format!("  depfile = {}\n", value(&d.display().to_string())))
                }
                // 束縛を書かないと `$depfile` は規則の側の同名を指し、
                // ninja が循環として断る。空は「依存ファイル無し」である
                // （[ADR-0048](../../../docs/adr/0048-assembly.md)）。
                None => out.push_str("  depfile =\n"),
            }
        }
        out.push('\n');
    }

    // 既定のターゲットは要求されたものの成果物と、計画に載った全ターゲットの
    // 派生。派生は誰の入力にもならないため、ここに並べなければ ninja からは
    // 到達せず、`artifacts` に書いた `.bin` が作られない（issue #60 / #64）。
    let defaults: Vec<String> =
        g.default_outputs.iter().map(|p| path(&p.display().to_string())).collect();
    if !defaults.is_empty() {
        out.push_str(&format!("default {}\n", defaults.join(" ")));
    }
    out
}

/// パスの位置での ninja エスケープ。空白と `:` が区切りとして効くため。
fn path(s: &str) -> String {
    s.replace('$', "$$").replace(' ', "$ ").replace(':', "$:")
}

/// 変数値の位置での ninja エスケープ。
fn value(s: &str) -> String {
    s.replace('$', "$$").replace('\n', " ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn path_escaping() {
        assert_eq!(path("/a/b c:d$e"), "/a/b$ c$:d$$e");
    }

    #[test]
    fn variable_value_escaping() {
        assert_eq!(value("cc -DX=$HOME"), "cc -DX=$$HOME");
    }
}
