//! ninja バックエンド。既定。
//!
//! コマンドは規則ではなく辺ごとの変数 `$cmd` に置く。フラグの組み立てを
//! ninja の変数展開に分散させず、1箇所（`Step::command_line`）に閉じるためである。
//! ninja 側の引用規則と自前の引用規則が二重に効く事故を避ける。

use crate::action::{breaks_the_line, cannot_spell, ActionKind};
use crate::backend::{Backend, BuildGraph};
use crate::exec::{drive, Failure};
use crate::toolstyle::{Deps, SHOW_INCLUDES_PREFIX};
use dowel_support::log_debug;
use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

pub struct Ninja;

pub const FILE: &str = "build.ninja";

impl Backend for Ninja {
    fn name(&self) -> &'static str {
        "ninja"
    }

    fn available(&self, probe: &mut crate::probe::Prober) -> bool {
        probe.responds_to_version("ninja")
    }

    fn emit(&self, g: &BuildGraph) -> Result<Vec<PathBuf>, Failure> {
        let path = g.build_dir.join(FILE);
        // 綴れるかを先に確かめる。書けないものを半分書いてから断ると、
        // 前回の ninja ファイルが壊れた状態で残る。
        let text = generate(g)?;
        std::fs::create_dir_all(&g.build_dir).and_then(|_| std::fs::write(&path, text)).map_err(
            |e| Failure::of("writing the ninja file", path.display().to_string(), e.to_string()),
        )?;
        log_debug!("wrote {}", path.display());
        Ok(vec![path])
    }

    fn run(&self, g: &BuildGraph, jobs: Option<usize>) -> Result<(), Failure> {
        let file = self.emit(g)?.remove(0);
        let mut args = vec!["-f".to_string(), file.display().to_string()];
        if let Some(j) = jobs {
            args.push("-j".into());
            args.push(j.to_string());
        }
        drive("ninja", &args, &g.build_dir)
    }
}

/// ninja ファイルの本文。綴れないものが在れば、書く前に断る（ADR-0058）。
pub fn generate(g: &BuildGraph) -> Result<String, Failure> {
    let mut out = String::new();
    out.push_str("# Generated by dowel. Do not edit by hand.\n");
    out.push_str("ninja_required_version = 1.10\n\n");

    out.push_str("rule cc\n");
    out.push_str("  command = $cmd\n");
    out.push_str("  description = $desc\n");
    match g.deps {
        // ヘッダ依存は深さ優先の再走査ではなくコンパイラの出力（depfile）から
        // 取る。
        //
        // `deps = gcc` は使わない。あれは読み取った `.d` を `.ninja_deps` へ
        // 畳んで消すため、依存の記録が ninja の実装詳細の中に閉じる。他の
        // バックエンドも同じ `.d` を読んで最新性を判定するので、記録は
        // バックエンドを跨いでディスク上に残す（issue #41）。
        Deps::Depfile => out.push_str("  depfile = $depfile\n\n"),
        // MSVC はコンパイラに記録を書かせない。`/showIncludes` の出力を
        // 拾うのは**実行する側**であり、ここでは ninja がそれを行う
        // （ADR-0027）。`.d` を跨いで共有する形は、書く者がいないので採れない。
        Deps::ShowIncludes => {
            out.push_str("  deps = msvc\n");
            out.push_str(&format!("  msvc_deps_prefix = {SHOW_INCLUDES_PREFIX}\n\n"));
        }
    }

    out.push_str("rule ar\n");
    out.push_str("  command = rm -f $out && $cmd\n");
    out.push_str("  description = $desc\n\n");

    out.push_str("rule link\n");
    out.push_str("  command = $cmd\n");
    out.push_str("  description = $desc\n\n");

    out.push_str("rule transform\n");
    out.push_str("  command = $cmd\n");
    out.push_str("  description = $desc\n\n");

    out.push_str("rule generate\n");
    out.push_str("  command = $cmd\n");
    out.push_str("  description = $desc\n\n");

    for step in &g.steps {
        spellable(step)?;
        let outputs: Vec<String> =
            step.outputs.iter().map(|p| path(&p.display().to_string())).collect();
        let inputs: Vec<String> =
            step.inputs.iter().map(|p| path(&p.display().to_string())).collect();
        // 宣言された辺のうち、入力に現れないものを順序専用の前提として置く。
        //
        // ninja が読むのはファイルの関係だけであり、計画の持つ `deps` は
        // 見ない（[ADR-0054](../../../../docs/adr/0054-generated-sources.md)
        // で測ったとおり）。ここに書かなければ、入力に現れない順序は ninja に
        // 伝わらない——make は前提条件として、direct は走らせる側の待ち行列と
        // して既に両方を見ており、揃えるのはこの1箇所である
        // （[ADR-0056](../../../../docs/adr/0056-direct-backend-parallelism.md)）。
        //
        // `||` にするのは、順序だけを言い、鮮度には効かせないためである。
        // 最新性が読むのは `inputs` であり、そこは direct と同じ判断にする。
        let known: BTreeSet<&Path> = step.inputs.iter().map(|p| p.as_path()).collect();
        let mut ordered: Vec<String> = step
            .deps
            .iter()
            .filter_map(|d| g.steps.get(*d))
            .flat_map(|dep| &dep.outputs)
            .filter(|o| !known.contains(o.as_path()))
            .map(|o| path(&o.display().to_string()))
            .collect();
        ordered.sort();
        ordered.dedup();

        out.push_str(&format!(
            "build {}: {} {}",
            outputs.join(" "),
            step.kind.name(),
            inputs.join(" ")
        ));
        if !ordered.is_empty() {
            out.push_str(&format!(" || {}", ordered.join(" ")));
        }
        out.push('\n');
        out.push_str(&format!("  cmd = {}\n", value(&step.command_line())));
        out.push_str(&format!("  desc = {}\n", value(&step.description)));
        if step.kind == ActionKind::Compile && g.deps == Deps::Depfile {
            match &step.depfile {
                Some(d) => {
                    out.push_str(&format!("  depfile = {}\n", value(&d.display().to_string())))
                }
                // 束縛を書かないと `$depfile` は規則の側の同名を指し、
                // ninja が循環として断る。空は「依存ファイル無し」である
                // （[ADR-0048](../../../docs/adr/0048-assembly.md)）。
                None => out.push_str("  depfile =\n"),
            }
        }
        out.push('\n');
    }

    // 既定のターゲットは要求されたものの成果物と、計画に載った全ターゲットの
    // 派生。派生は誰の入力にもならないため、ここに並べなければ ninja からは
    // 到達せず、`artifacts` に書いた `.bin` が作られない（issue #60 / #64）。
    // 既定のターゲットは辺の外に在る。ステップを1つずつ見るだけでは届かない。
    for out in &g.default_outputs {
        let shown = out.display().to_string();
        if let Some(c) = breaks_the_line(&shown) {
            return Err(Failure::of(
                "generating the ninja file",
                shown.clone(),
                cannot_spell("ninja", "a default target", c, &shown),
            ));
        }
    }
    let defaults: Vec<String> =
        g.default_outputs.iter().map(|p| path(&p.display().to_string())).collect();
    if !defaults.is_empty() {
        out.push_str(&format!("default {}\n", defaults.join(" ")));
    }
    Ok(out)
}

/// このステップを ninja の綴りに落とせるか（ADR-0058）。
///
/// 落とせないものを黙って書き換えない。かつては命令の中の改行を空白に
/// 置き換えており、`printf '#define A 1\n#define B 2\n'` はマクロ1つ分の
/// 行を書いた——ビルドは成功し、出来上がったものだけが違った。
///
/// 見るのは**1行として書き出すものすべて**である。命令だけ、あるいは入出力
/// だけを見ると、見ていない欄を通って同じ壊れ方が戻る——`depfile` は
/// `depfile = <path>` という1行であり、辺の中には現れない。
fn spellable(step: &crate::backend::Step) -> Result<(), Failure> {
    let paths = step
        .inputs
        .iter()
        .chain(&step.outputs)
        .chain(&step.depfile)
        .map(|p| p.display().to_string());
    for text in [step.command_line(), step.description.clone()].into_iter().chain(paths) {
        let Some(c) = breaks_the_line(&text) else { continue };
        return Err(Failure::of(
            "generating the ninja file",
            step.command_line(),
            cannot_spell("ninja", "a build edge", c, &step.description),
        ));
    }
    Ok(())
}

/// パスの位置での ninja エスケープ。空白と `:` が区切りとして効くため。
fn path(s: &str) -> String {
    s.replace('$', "$$").replace(' ', "$ ").replace(':', "$:")
}

/// 変数値の位置での ninja エスケープ。
///
/// 行を終わらせる文字は**ここでは扱わない**。かつては改行を空白に置き換えて
/// いたが、それは綴れないものを黙って別のものにする経路だった（ADR-0058）。
/// 綴れるかどうかは [`spellable`] が先に断る。
fn value(s: &str) -> String {
    s.replace('$', "$$")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn path_escaping() {
        assert_eq!(path("/a/b c:d$e"), "/a/b$ c$:d$$e");
    }

    #[test]
    fn variable_value_escaping() {
        assert_eq!(value("cc -DX=$HOME"), "cc -DX=$$HOME");
    }

    fn step(
        id: usize,
        inputs: &[&str],
        outputs: &[&str],
        deps: Vec<usize>,
    ) -> crate::backend::Step {
        crate::backend::Step {
            id,
            kind: ActionKind::Compile,
            target: "p:t".into(),
            description: format!("step {id}"),
            program: "true".into(),
            arguments: vec![],
            inputs: inputs.iter().map(PathBuf::from).collect(),
            outputs: outputs.iter().map(PathBuf::from).collect(),
            depfile: None,
            deps,
            cwd: None,
        }
    }

    fn graph_of(steps: Vec<crate::backend::Step>) -> BuildGraph {
        BuildGraph {
            build_dir: PathBuf::from("/b"),
            steps,
            artifacts: vec![],
            deps: Deps::Depfile,
            default_outputs: vec![],
            tool_stamps: vec![],
        }
    }

    #[test]
    fn a_declared_edge_no_file_carries_becomes_an_order_only_prerequisite() {
        // ninja は計画の辺を読まない。書かなければ、入力に現れない順序は
        // 伝わらないままである（ADR-0056）。
        let text = generate(&graph_of(vec![
            step(0, &[], &["/b/gen/x.h"], vec![]),
            step(1, &["/s/b.c"], &["/b/b.o"], vec![0]),
        ]))
        .expect("this graph is spellable");
        assert!(text.contains("build /b/b.o: cc /s/b.c || /b/gen/x.h\n"), "{text}");
    }

    #[test]
    fn a_command_with_a_newline_is_refused_rather_than_flattened() {
        // 空白に置き換えていた頃は、この命令が別の命令として綴られ、
        // ビルドは成功していた（ADR-0058）。
        let mut s = step(0, &[], &["/b/cfg.h"], vec![]);
        s.arguments = vec!["-c".into(), "printf 'a\nb'".into()];
        let e = generate(&graph_of(vec![s])).expect_err("a newline is not spellable");
        let text = format!("{e}");
        assert!(text.contains("newline"), "{text}");
        assert!(text.contains("--backend=direct"), "{text}");
    }

    #[test]
    fn a_depfile_with_a_newline_is_refused() {
        // `depfile = <path>` も1行である。ステップの入出力だけを見ていると
        // ここを素通りし、壊れた ninja ファイルを書いてしまう。
        let mut st = step(0, &["/s/a.c"], &["/b/a.o"], vec![]);
        st.depfile = Some(PathBuf::from("/b/a\n.o.d"));
        let e = generate(&graph_of(vec![st])).expect_err("a newline is not spellable");
        assert!(format!("{e}").contains("newline"), "{e}");
    }

    #[test]
    fn a_default_target_with_a_newline_is_refused() {
        // `default <paths>` も1行である。辺の外に在るので、ステップを1つずつ
        // 見るだけでは届かない。
        let mut g = graph_of(vec![step(0, &["/s/a.c"], &["/b/a.o"], vec![])]);
        g.default_outputs = vec![PathBuf::from("/b/a\npp")];
        let e = generate(&g).expect_err("a newline is not spellable");
        assert!(format!("{e}").contains("newline"), "{e}");
    }

    #[test]
    fn an_edge_the_inputs_already_carry_is_not_repeated() {
        // 入力に在るものを順序専用にも並べると、同じ関係が2つの綴りで
        // 書かれる。読み手にとっては同じだが、意味の重複は取り除く。
        let text = generate(&graph_of(vec![
            step(0, &["/s/a.c"], &["/b/a.o"], vec![]),
            step(1, &["/b/a.o"], &["/b/app"], vec![0]),
        ]))
        .expect("this graph is spellable");
        assert!(text.contains("build /b/app: cc /b/a.o\n"), "{text}");
    }
}
