//! `dowel.lock` — 外部依存の解決結果の記録（[ADR-0015]）。
//!
//! `path` はローカルの内容そのもの、`git` は rev が内容を固定するため、
//! いずれもロックを要さない。ロックが要るのは解決が環境に依存する形態
//! （pkg-config）であり、記録の目的は**環境の漂流の検出**である。
//! システムパッケージは取得できないため、ロックは復元を約束しない。
//! 約束するのは「前回と違うものを黙って使わない」ことである。
//!
//! - 記録が無い依存は、解決結果を追記して書く
//! - 記録と一致すれば何もしない
//! - 記録と食い違えば `lockfile-drift` の警告を出し、**書き換えない**。
//!   新しい解決を受け入れるには、当該項目（またはファイル）を消す
//!
//! [ADR-0015]: ../../../docs/adr/0015-version-deps-pkgconfig.md

use dowel_support::{Diagnostic, FileId};
use std::path::Path;

pub const LOCK_NAME: &str = "dowel.lock";

const HEADER: &str = "\
# Generated by dowel. It records resolved external dependencies so that a
# changed environment is noticed instead of silently used. Delete an entry
# (or this file) to accept a different resolution.
";

/// 解決結果を記録と突き合わせる。漂流していれば警告を返す。
pub fn reconcile(
    root: &Path,
    name: &str,
    version: &str,
    source: &str,
    site: dowel_eval::Site,
) -> Option<Diagnostic> {
    let path = root.join(LOCK_NAME);
    let text = std::fs::read_to_string(&path).unwrap_or_default();

    if let Some(locked) = find(&text, name, source) {
        if locked == version {
            return None;
        }
        return Some(
            Diagnostic::warning(
                "lockfile-drift",
                format!("`{name}` resolved to {version}, but {LOCK_NAME} records {locked}"),
            )
            .at(site.file, site.span, "declared here")
            .note("the system package changed since the lock was written")
            .note(format!(
                "to accept {version}, delete the `{name}` entry from {LOCK_NAME} (or the file)"
            )),
        );
    }

    // 追記して書く。厳密な TOML では配列テーブルの位置に意味が無い。
    let mut out = if text.is_empty() { HEADER.to_string() } else { text };
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out.push_str(&format!(
        "\n[[package]]\nname    = \"{name}\"\nversion = \"{version}\"\nsource  = \"{source}\"\n"
    ));
    // 書けなくても誤りではない。次回も解決し直すだけで、結果は変わらない。
    let _ = std::fs::write(&path, out);
    None
}

/// 記録から1件を引く。読めない記録は無いものとして扱う。
fn find(text: &str, name: &str, source: &str) -> Option<String> {
    let parsed = dowel_syntax::parse(text, FileId(0));
    let (doc, _) = dowel_eval::eval(&parsed.root, text, FileId(0));
    for t in doc.tables_under(&["package"]) {
        if t.path.len() != 1 {
            continue;
        }
        let field = |k: &str| t.entry(k).and_then(|e| e.value.as_str().map(str::to_string));
        if field("name").as_deref() == Some(name) && field("source").as_deref() == Some(source) {
            return field("version");
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn entries_are_found_by_name_and_source() {
        let text = "[[package]]\nname = \"zlib\"\nversion = \"1.3\"\nsource = \"pkg-config\"\n";
        assert_eq!(find(text, "zlib", "pkg-config"), Some("1.3".into()));
        assert_eq!(find(text, "zlib", "registry"), None);
        assert_eq!(find(text, "png", "pkg-config"), None);
        assert_eq!(find("", "zlib", "pkg-config"), None);
    }
}
