[package]
name = "dowel-build"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Action graph, ninja generation, compile_commands.json, and execution."

[dependencies]
dowel-support.workspace = true
dowel-syntax.workspace = true
dowel-eval.workspace = true
dowel-model.workspace = true
dowel-store.workspace = true
